CREATE TABLE IF NOT EXISTS Time(Time TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS Temperature(
	Time TEXT PRIMARY KEY,
	Value REAL NOT NULL,	
	FOREIGN KEY(Time) REFERENCES Time(Time)
);
CREATE TABLE IF NOT EXISTS Humidity(
	Time TEXT PRIMARY KEY,
	Value REAL NOT NULL,	
	FOREIGN KEY(Time) REFERENCES Time(Time)
);